# before_script:
stages:
  - build
  - migrate
  - deploy

build:
  stage: build
  script: 
    - /opt/env_files/antarctic_build.sh
    - docker-compose build --no-cache
  only:
    - master
  tags:
    - build
    - shell

analyze:
  stage: analyze
  script:
    - /opt/env_files/antarctic_build.sh
    - CI=true dive antarctic-map:latest
  only:
    - master
  tags:
    - build
    - shell  

migrate:
  stage: migrate
  script: 
    - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    - /opt/env_files/antarctic_build.sh
    - export DJANGO_SETTINGS_MODULE="map.settings_docker_build"
    - pip3 install -U pip
    - pip3 install --no-cache -r requirements.txt
    - python3 manage.py migrate
  only:
    - master
  tags:
    - deploy
    - shell

deploy_prod:
  stage: deploy
  script:
    - docker-compose up --force-recreate -d
    - docker container prune -f
    - docker image prune -a -f
  environment:
    name: production
  only:
    - master
  tags:
    - deploy
    - shell