# before_script:
stages:
  - build
  - test
  - analyze
  - migrate
  - deploy

build:
  stage: build
  script:
    - docker-compose build --no-cache
    - docker push registry.gitlab.com/freeyeti/antarctic-map
  only:
    - master
  tags:
    - build
    - shell

test-backend:
  stage: test
  script:
    # With docker-compose
    # - docker-compose -f docker-compose.test.yml run antarctic_map_test
    # - docker-compose -f docker-compose.test.yml down
    #
    # In kubernetes (should be sure config maps applied first)
    - microk8s kubectl apply -f deployment.test.yml
    - microk8s kubectl logs -f antarctic-map-test
    - microk8s kubectl delete -f deployment.test.yml
  only:
    - master
  tags:
    - build
    - shell

analyze:
  stage: analyze
  script:
    - CI=true dive registry.gitlab.com/freeyeti/antarctic-map:latest
  only:
    - master
  tags:
    - build
    - shell

migrate:
  stage: migrate
  script:
    # Use system python
    # - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    # - export DJANGO_SETTINGS_MODULE="map.settings_docker_build"
    # - pip3 install -U pip
    # - pip3 install --no-cache -r requirements.txt
    # - python3 manage.py migrate

    # In kubernetes (should be sure config maps applied first)
    - microk8s kubectl apply -f deployment.migrate.yml
    - microk8s kubectl logs -f antarctic-map-migrate
    - microk8s kubectl delete -f deployment.migrate.yml
  only:
    - master
  tags:
    - deploy
    - shell

deploy_prod:
  stage: deploy
  script:
    - docker-compose up --force-recreate -d
    - docker container prune -f
    - docker image prune -a -f
  environment:
    name: production
  only:
    - master
  tags:
    - deploy
    - shell
