# before_script:
stages:
  - build
  - test
  - analyze
  - migrate
  - deploy

build:
  stage: build
  script: 
    - docker-compose build --no-cache
  only:
    - master
  tags:
    - build
    - shell

test-backend:
  stage: test
  script: 
    - docker-compose -f docker-compose.test.yml run antarctic_map_test
    - docker-compose -f docker-compose.test.yml down
  only:
    - master
  tags:
    - build
    - shell

analyze:
  stage: analyze
  script:
    - CI=true dive antarctic-map:latest
  only:
    - master
  tags:
    - build
    - shell  

migrate:
  stage: migrate
  script: 
    - export PATH="/home/gitlab-runner/.local/bin:$PATH"
    - export DJANGO_SETTINGS_MODULE="map.settings_docker_build"
    - pip3 install -U pip
    - pip3 install --no-cache -r requirements.txt
    - python3 manage.py migrate
  only:
    - master
  tags:
    - deploy
    - shell

deploy_prod:
  stage: deploy
  script:
    - docker-compose up --force-recreate -d
    - docker container prune -f
    - docker image prune -a -f
  environment:
    name: production
  only:
    - master
  tags:
    - deploy
    - shell