apiVersion: batch/v1
kind: Job
metadata:
  name: antarctic-map-test
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 600
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
      containers:
        - name: antarctic-map-test
          image: registry.gitlab.com/freeyeti/antarctic-map
          imagePullPolicy: IfNotPresent
          command: ["./docker-entrypoint-test.sh"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: map.settings_docker_build
