apiVersion: batch/v1
kind: Job
metadata:
  name: antarctic-map-migrate
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
      backoffLimit: 4
      activeDeadlineSeconds: 300
      containers:
        - name: antarctic-map-migrate
          image: registry.gitlab.com/freeyeti/antarctic-map
          imagePullPolicy: IfNotPresent
          command: ["python3", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: map.settings_docker_build
