version: "3.5"

services:
  antarctic_map:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEOSERVER_URL_VAR=https://geo.freeyeti.net/geoserver/
    image: registry.gitlab.com/freeyeti/antarctic-map:__IMAGE_TAG__
