version: "3.5"

services:
  database:
    image: postgis/postgis:13-3.0
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=antarctic
      - POSTGRES_USER=antarctic
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    image: freeyeti/dev-in-docker:python3-pyspark
    environment:
      - DJANGO_SETTINGS_MODULE=map.settings_dev
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/code
      - ${GIS_DATA_DIR}:/data
    depends_on:
      - database
  frontend:
    image: freeyeti/dev-in-docker:node-yarn
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - .:/code
