apiVersion: batch/v1
kind: Job
metadata:
  name: antarctic-map-migrate
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
      containers:
        - name: antarctic-map-migrate
          image: __IMAGE_DJANGO__:__IMAGE_TAG__
          imagePullPolicy: Always
          command: ["./manage", "migrate"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: map.settings_docker_build
