apiVersion: batch/v1
kind: Job
metadata:
  name: antarctic-map-django-test
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      imagePullSecrets:
        - name: yeti2-pull-secret
      restartPolicy: Never
      containers:
        - name: antarctic-map-django-test
          image: __IMAGE_DJANGO__:__IMAGE_TAG__
          imagePullPolicy: IfNotPresent
          command: ["./report"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: map.settings_docker_build
          volumeMounts:
            - name: gis-data
              mountPath: /data
      volumes:
        - name: gis-data
          hostPath:
            path: __ANTARCTIC_MAP_GIS_DATA__
