apiVersion: batch/v1
kind: Job
metadata:
  name: antarctic-map-django-test
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      imagePullSecrets:
        - name: yeti2-pull-secret
      restartPolicy: Never
      containers:
        - name: antarctic-map-django-test
          image: freeyeti/dev-in-docker:python3-gis
          imagePullPolicy: Always
          command: ["./docker-entrypoint-test.sh"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: map.settings_docker_build
          volumeMounts:
            - name: code
              mountPath: /code
      volumes:
        - name: code
          hostPath:
            path: __CODE_PATH__
